### ISSUE TITLE
No images appearing for profile or project sections

### ISSUE THREAD

**Issue by ajandaur** [gurusabarish/hugo-profile#48]
I am trying to replace the profile picture as well as the project section pictures and I followed the directions to put the images in 
`website/static/images`

When I try to refer to the image in my config file:
`profile_image: "website/static/images/profile.png"`

However, the image does not show up at all and I'm not sure what I am doing wrong.

The config file is at the root directory, should it be within the website folder?

Thanks!

**Comment by gurusabarish** [comment]
Hii @ajandaur 
> profile_image: "website/static/images/profile.png"

Please don't use `website/static/.....`. It doesn't make sense. The files inside the static folder will be palced in root after build. So,

Use this [like this](https://github.com/gurusabarish/hugo-profile/blob/00c24c1e15e6c6e6a9d1b8b31a0df16630548574/website/v3.yaml#L57) in your config file for all images
`profile_image: "/images/....."`

> The config file is at the root directory, should it be within the website folder?

If you are using with direct deployment with GitHub, file should be in website folder. Otherwise, file should be in root

Thanks

**Comment by ajandaur** [comment]
Hey @gurusabarish! 

> Please don't use website/static/...... It doesn't make sense. The files inside the static folder will be palced in root after build. So,

> Use this [like this](https://github.com/gurusabarish/hugo-profile/blob/00c24c1e15e6c6e6a9d1b8b31a0df16630548574/website/v3.yaml#L57) in your config file for all images
> profile_image: "/images/....."

Appreciate the reply. I actually cloned the repo for local development but I did as you outlined above as I still don't get my profile image to show up. I placed the image files in the correct folder /images.

`  profile_image: "/images/profile.png"`

<img width="369" alt="Screen Shot 2022-02-06 at 11 15 48 AM" src="https://user-images.githubusercontent.com/35319467/152697534-717da0c2-124d-4284-b023-9736b161c967.png">
